# Generated by Django 2.0.1 on 2018-01-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('coord_x', models.PositiveIntegerField()),
                ('coord_y', models.PositiveIntegerField()),
            ],
        ),
    ]
